# Generated by Django 4.1 on 2023-01-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_creator_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='userLikes', to='network.like'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
