# Generated by Django 4.1 on 2023-03-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='date',
        ),
    ]
